# Generated by Django 3.2.7 on 2021-09-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('blood', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
            ],
        ),
    ]
