# Generated by Django 3.2.7 on 2021-09-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpimp', models.ImageField(upload_to='assets/images')),
                ('name', models.CharField(max_length=30)),
                ('blood', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=25)),
                ('dob', models.CharField(max_length=10)),
            ],
        ),
    ]
