# Generated by Django 3.2.7 on 2021-09-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='haveimg',
            field=models.BooleanField(default=False),
        ),
    ]
