# Generated by Django 3.2.7 on 2021-09-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
    ]
