# Generated by Django 3.2.7 on 2021-09-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_alter_reguser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
    ]
