# Generated by Django 3.2.7 on 2021-09-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_user_haveimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
